
package com.foriba.esmm;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ForibaESmmServicesPort", targetNamespace = "http://foriba.com/eSmm/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ ObjectFactory.class })
public interface ForibaESmmServicesPort {

	/**
	 * 
	 * @param parameter
	 * @return returns com.foriba.esmm.SendDocumentResponse
	 * @throws SendDocumentFaultMessage
	 */
	@WebMethod(action = "sendDocument")
	@WebResult(name = "sendDocumentResponse", targetNamespace = "http://foriba.com/eSmm/", partName = "parameter")
	public SendDocumentResponse sendDocument(
			@WebParam(name = "sendDocumentRequest", targetNamespace = "http://foriba.com/eSmm/", partName = "parameter") SendDocumentRequest parameter)
			throws SendDocumentFaultMessage;

	/**
	 * 
	 * @param parameter
	 * @return returns com.foriba.esmm.GetDocumentResponse
	 * @throws GetDocumentFaultMessage
	 */
	@WebMethod(action = "getDocument")
	@WebResult(name = "getDocumentResponse", targetNamespace = "http://foriba.com/eSmm/", partName = "parameter")
	public GetDocumentResponse getDocument(
			@WebParam(name = "getDocumentRequest", targetNamespace = "http://foriba.com/eSmm/", partName = "parameter") GetDocumentRequest parameter)
			throws GetDocumentFaultMessage;

	/**
	 * 
	 * @param parameter
	 * @return returns com.foriba.esmm.GetReportListResponse
	 * @throws GetReportListFaultMessage
	 */
	@WebMethod(action = "getReportList")
	@WebResult(name = "getReportListResponse", targetNamespace = "http://foriba.com/eSmm/", partName = "parameter")
	public GetReportListResponse getReportList(
			@WebParam(name = "getReportListRequest", targetNamespace = "http://foriba.com/eSmm/", partName = "parameter") GetReportListRequest parameter)
			throws GetReportListFaultMessage;

	/**
	 * 
	 * @param parameter
	 * @return returns com.foriba.esmm.GetReportDataResponse
	 * @throws GetReportDataFaultMessage
	 */
	@WebMethod(action = "getReportData")
	@WebResult(name = "getReportDataResponse", targetNamespace = "http://foriba.com/eSmm/", partName = "parameter")
	public GetReportDataResponse getReportData(
			@WebParam(name = "getReportDataRequest", targetNamespace = "http://foriba.com/eSmm/", partName = "parameter") GetReportDataRequest parameter)
			throws GetReportDataFaultMessage;

	/**
	 * 
	 * @param parameter
	 * @return returns com.foriba.esmm.CancelDocumentResponse
	 * @throws CancelDocumentFaultMessage
	 */
	@WebMethod(action = "cancelDocument")
	@WebResult(name = "cancelDocumentResponse", targetNamespace = "http://foriba.com/eSmm/", partName = "parameter")
	public CancelDocumentResponse cancelDocument(
			@WebParam(name = "cancelDocumentRequest", targetNamespace = "http://foriba.com/eSmm/", partName = "parameter") CancelDocumentRequest parameter)
			throws CancelDocumentFaultMessage;

}
